sylius_ui:
    events:
        sylius.shop.register.form:
            blocks:
                monsieurbiz_anti_spam_shop_register:
                    template: '@MonsieurBizSyliusAntiSpamPlugin/Shop/form_captcha.html.twig'
        sylius.shop.contact.request.form:
            blocks:
                monsieurbiz_anti_spam_shop_contact:
                    template: '@MonsieurBizSyliusAntiSpamPlugin/Shop/form_captcha.html.twig'
        sylius.admin.layout.javascripts:
            blocks:
                monsieurbiz_anti_spam_admin_quarantine_details:
                    template: '@MonsieurBizSyliusAntiSpamPlugin/Admin/Grid/Field/quarantine_item_js.html.twig'
